import { WorkItem, Partner } from './types';

export const siteCopy = {
  headline: 'YOUR MERCH PARTNER.',
  subhead:
    'Most printers take your order and hand it back. We work alongside you to figure out the right production model—and put our own resources on the line to make it work.',
};

export const services = [
  {
    id: 'traditional',
    title: 'Traditional Production',
    tagline: 'The model you already know.',
    body: 'We work with you on the design, you choose your garments, sizes, colors and quantities, and we decorate everything and deliver the finished order to you.',
    icon: '01',
  },
  {
    id: 'flexible',
    title: 'Flexible Merch Production',
    tagline: 'Your screen printing, applied on your schedule.',
    body: 'You pay for your screen printing upfront—we print your artwork onto transfer sheets instead of directly onto garments. That means your prints aren\'t tied to any specific blank. Use them on t-shirts today, hoodies next month, or a different colorway entirely. Quantity pricing on the screen printing without having to predict exactly what you\'ll need or when.',
    icon: '02',
  },
  {
    id: 'mobile',
    title: 'Mobile Merch',
    tagline: 'We Bring The Shop. You Bring The Demand. We Split The Profit.',
    body: 'You pay for your screen printing—we print your artwork onto transfer sheets so they can be applied on-site at the event. You also put down an operational deposit covering our labor, travel, and event overhead. We stock and reuse the blank garments ourselves across events. Event sales return your deposit first, then we split what\'s left. We only win when you do—and when the event ends, there\'s no unsold inventory for you to figure out how to store or sell.',
    icon: '03',
    featured: true,
  },
];

export const recentWork: WorkItem[] = [
  {
    slug: 'penn-vs-usc-showdown',
    title: 'Penn State vs USC Tailgate Tee',
    thumbnail: '/images/work/PennXUSC.png',
    images: ['/images/work/PennXUSC.png'],
    tags: ['College', 'Event Tee', 'Rivalry'],
    year: 2024,
    productionModel: 'traditional',
    context: 'One-time rivalry event with a fixed date and known headcount—traditional bulk order was the right fit.',
  },
  {
    slug: 'colony-cinco-anos',
    title: 'Colony Ghost Kitchen — 5th Anniversary',
    thumbnail: '/images/work/ColonyCincoAnosFront.png',
    images: ['/images/work/ColonyCincoAnosFront.png'],
    tags: ['Food', 'Anniversary', 'Small Business'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Ghost kitchen celebrating five years in business. Printing to transfer sheets let them sell tees to loyal customers in small batches without committing to a full inventory run.',
  },
  {
    slug: 'eagles-nest-west',
    title: 'Eagles Nest West Club Tee',
    thumbnail: '/images/work/EaglesNestWestFront.png',
    images: ['/images/work/EaglesNestWestFront.png', '/images/work/EaglesNestWestBack.png'],
    tags: ['Club', 'Lifestyle'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Growing fan club needed an ongoing supply without committing to garment styles upfront—paying for the screen printing and applying it to blanks later gave them flexibility as the group expanded.',
  },
  {
    slug: 'interstellar',
    title: 'Interstellar Restaurant & Coffee',
    thumbnail: '/images/work/InterstellarFront.png',
    images: ['/images/work/InterstellarFront.png', '/images/work/InterstellarBack.png'],
    tags: ['Coffee', 'Restaurant', 'Small Business'],
    year: 2024,
    productionModel: 'traditional',
    context: 'Small restaurant and coffee shop wanting branded tees for their team—clean design, small batch, one run.',
  },
  {
    slug: 'philthy-design',
    title: 'Eagles x Brit — Philthy Collab Tee',
    thumbnail: '/images/work/PhilthyFront.png',
    images: ['/images/work/PhilthyFront.png', '/images/work/PhilthyBack.png'],
    tags: ['Eagles', 'Football', 'Collab'],
    year: 2025,
    productionModel: 'flexible',
    context: 'A collab between Eagles Nest West and Britannia Pub to mark an iconic moment in the Eagles\' Super Bowl winning season. Demand was so high it sold out every batch—flexible printing meant they could restock quickly without reordering the artwork.',
  },
  {
    slug: 'good-people-advisory',
    title: 'Good People Coffee',
    thumbnail: '/images/work/GoodPeopleAdvisoryBack.png',
    images: ['/images/work/GoodPeopleAdvisoryBack.png'],
    tags: ['Coffee', 'Small Business', 'Community'],
    year: 2024,
    productionModel: 'traditional',
    context: 'Local minority and female owned coffee shop wanted branded tees for their staff and regulars—small batch, one run.',
  },
  {
    slug: 'san-remo-not-like-us',
    title: 'San Remo Barista Competition Tee',
    thumbnail: '/images/work/SanRemoNotLikeUs.png',
    images: ['/images/work/SanRemoNotLikeUs.png'],
    tags: ['Coffee', 'Competition', 'Corporate'],
    year: 2024,
    productionModel: 'traditional',
    context: 'San Remo, an Italian coffee machine manufacturer, needed event tees for a barista competition they were sponsoring—set headcount, one delivery, done.',
  },
  {
    slug: 'sf-fsu-design',
    title: 'SF FSU Design',
    thumbnail: '/images/work/SFFSU.png',
    images: ['/images/work/SFFSU.png'],
    tags: ['College', 'SF'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Alumni fan club using the same design across multiple SF watch parties—paying for the screen printing upfront let them apply prints to new blanks each season without reordering the artwork.',
  },
  {
    slug: 'brit-since-96',
    title: 'Britannia Pub — Since \'96',
    thumbnail: '/images/work/BritSince96.png',
    images: ['/images/work/BritSince96.png'],
    tags: ['Bar', 'Pub', 'Anniversary'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Britannia Pub celebrating their anniversary with a merch run—printing to transfer sheets let them restock tees across multiple events without reordering the artwork.',
  },
  {
    slug: 'hermosa-ink',
    title: 'Hermosa Ink Pinup Tee',
    thumbnail: '/images/work/hermosa-ink-colorways.jpg',
    images: ['/images/work/hermosa-ink-colorways.jpg'],
    tags: ['Tattoo', 'Art', 'Colorways'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Tattoo shop launching a signature artist tee across six colorways—printing to transfer sheets meant one screen printing run covered every color option without locking into any specific blank.',
  },
  {
    slug: 'coach-damon',
    title: 'Coach Damon Wrap Em Up Tee',
    thumbnail: '/images/work/coach-damon-colorways.jpg',
    images: ['/images/work/coach-damon-colorways.jpg'],
    tags: ['College', 'FSU', 'Parody'],
    year: 2024,
    productionModel: 'traditional',
    context: 'One-off parody drop for an FSU alumni club—limited run, single delivery, not meant to repeat.',
  },
  {
    slug: 'wildherness',
    title: 'Wildherness Graphic Tee',
    thumbnail: '/images/work/wildherness-colorways.jpg',
    images: ['/images/work/wildherness-colorways.jpg'],
    tags: ['Nonprofit', 'Women', 'Outdoor'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Women\'s nonprofit introducing more women to hunting, fishing, and camping. Printing to transfer sheets let them offer their design across multiple colorways without over-ordering—important when you\'re a nonprofit watching every dollar.',
  },
  {
    slug: 'solo-leveling-twitchcon',
    title: 'Solo Leveling Overdrive x TwitchCon',
    thumbnail: '/images/work/solo-leveling-twitchcon.jpg',
    images: ['/images/work/solo-leveling-twitchcon.jpg', '/images/work/solo-leveling-twitchcon-white.jpg'],
    tags: ['Gaming', 'Event', 'Convention'],
    year: 2024,
    productionModel: 'traditional',
    context: 'Gaming brand needed event tees for TwitchCon in two colorways—defined convention date, known order size, single run.',
  },
  {
    slug: 'stubhub-open-distribution',
    title: 'StubHub x Open Distribution Cap',
    thumbnail: '/images/work/stubhub-open-distribution.jpg',
    images: ['/images/work/stubhub-open-distribution.jpg'],
    tags: ['Corporate', 'Collab', 'Cap'],
    year: 2024,
    productionModel: 'traditional',
    context: 'Small batch for one internal team on a tight turnaround—we hit the deadline with no minimum quantity requirements.',
  },
  {
    slug: 'love-is-punk-rock',
    title: 'Love Is Punk Rock Trucker Hat',
    thumbnail: '/images/work/love-is-punk-rock-colorways.jpg',
    images: ['/images/work/love-is-punk-rock-colorways.jpg'],
    tags: ['Music', 'Hat', 'Colorways'],
    year: 2024,
    productionModel: 'flexible',
    context: 'An original 687 design. Printing to transfer sheets let us produce small batches for different events on demand—same artwork, applied whenever and wherever we needed it.',
  },
  {
    slug: 'fsu-seminole-la',
    title: 'FSU Seminole Club LA',
    thumbnail: '/images/work/fsu-seminole-la-grey.jpg',
    images: ['/images/work/fsu-seminole-la-grey.jpg'],
    tags: ['College', 'Alumni', 'Club'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Alumni fan club chapter sharing the same design across multiple events—prints bought upfront and applied to blanks as the season progressed.',
  },
  {
    slug: 'eagles-nest-britannia',
    title: 'Eagles Nest West x Britannia Pub',
    thumbnail: '/images/work/eagles-nest-britannia-green.jpg',
    images: ['/images/work/eagles-nest-britannia-green.jpg'],
    tags: ['Club', 'Bar', 'Event'],
    year: 2025,
    productionModel: 'flexible',
    context: 'Eagles Nest West running the same design at the Britannia Pub—screen printing to transfers let them restock each watch party without having to reorder.',
  },
  {
    slug: 'cc-surface-restoration',
    title: 'CC Surface Restoration',
    thumbnail: '/images/work/cc-surface-restoration.jpg',
    images: ['/images/work/cc-surface-restoration.jpg'],
    tags: ['Local Business', 'Uniform', 'Branded'],
    year: 2025,
    productionModel: 'traditional',
    context: 'Local service business needing branded crew tees—defined headcount, consistent colorway, single run.',
  },
];

export const partners: Partner[] = [
  { name: 'Sony Pictures', logo: '/images/partners/sony.png' },
  { name: 'Colony', logo: '/images/partners/colony.png' },
  { name: 'FSU SF', logo: '/images/partners/fsu-sf.webp' },
  { name: 'Brit', logo: '/images/partners/brit.webp' },
  { name: 'Good People', logo: '/images/partners/good-people.webp' },
  { name: 'San Remo', logo: '/images/partners/san-remo.webp' },
];