import { WorkItem, Partner } from './types';

export const siteCopy = {
  headline: 'YOUR MERCH PARTNER.',
  subhead:
    'Most printers take your order and hand it back. We work alongside you to figure out the right production model—and put our own resources on the line to make it work.',
};

export const services = [
  {
    id: 'traditional',
    title: 'Traditional Production',
    tagline: 'The straightforward option.',
    body: 'We work with you on the design, you choose your garments, sizes, colors and quantities, and we decorate everything and deliver the finished order to you.',
    icon: '01',
  },
  {
    id: 'flexible',
    title: 'Flexible Merch Production',
    tagline: 'Your screen printing, applied on your schedule.',
    body: 'You pay for your screen printing upfront—we print your artwork onto transfer sheets instead of directly onto garments. That means your prints aren\'t tied to any specific blank. Use them on t-shirts today, hoodies next month, or a different colorway entirely. Quantity pricing on the screen printing without having to predict exactly what you\'ll need or when.',
    icon: '02',
  },
  {
    id: 'mobile',
    title: 'Mobile Merch',
    tagline: 'We bring the shop. You keep the upside.',
    body: 'You pay for your screen printing—we print your artwork onto transfer sheets so they can be applied on-site at the event. You also put down an operational deposit covering our labor, travel, and event overhead. We bring the blank garments, van, equipment, and staff entirely at our cost. Event sales return your deposit first, then we split what\'s left. We only win when you do—and you leave with zero finished inventory.',
    icon: '03',
    featured: true,
  },
];

export const recentWork: WorkItem[] = [
  {
    slug: 'penn-vs-usc-showdown',
    title: 'Penn State vs USC Tailgate Tee',
    thumbnail: '/images/work/PennXUSC.png',
    images: ['/images/work/PennXUSC.png'],
    tags: ['College', 'Event Tee', 'Rivalry'],
    year: 2024,
    productionModel: 'traditional',
    context: 'One-time rivalry event with a fixed date and known headcount—traditional bulk order was the right fit.',
  },
  {
    slug: 'colony-cinco-anos',
    title: 'Colony Cinco Años Tee',
    thumbnail: '/images/work/ColonyCincoAnosFront.png',
    images: ['/images/work/ColonyCincoAnosFront.png'],
    tags: ['Logo', 'Anniversary', 'Retro'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Bar wanted to sell tees to regulars without over-ordering. Paying for the screen printing upfront let them apply prints to new blanks in small batches as demand came in.',
  },
  {
    slug: 'eagles-nest-west',
    title: 'Eagles Nest West Club Tee',
    thumbnail: '/images/work/EaglesNestWestFront.png',
    images: ['/images/work/EaglesNestWestFront.png', '/images/work/EaglesNestWestBack.png'],
    tags: ['Club', 'Lifestyle'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Growing fan club needed an ongoing supply without committing to garment styles upfront—paying for the screen printing and applying it to blanks later gave them flexibility as the group expanded.',
  },
  {
    slug: 'interstellar',
    title: 'Interstellar Graphic Tee',
    thumbnail: '/images/work/InterstellarFront.png',
    images: ['/images/work/InterstellarFront.png', '/images/work/InterstellarBack.png'],
    tags: ['Graphic', 'Space', 'Movie'],
    year: 2024,
    productionModel: 'traditional',
    context: 'Limited-run for a film screening event—defined quantity, single delivery, no need for ongoing production.',
  },
  {
    slug: 'philthy-design',
    title: 'Philthy Custom Design',
    thumbnail: '/images/work/PhilthyFront.png',
    images: ['/images/work/PhilthyFront.png', '/images/work/PhilthyBack.png'],
    tags: ['Custom', 'Street'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Independent label testing multiple colorways—paying for the screen printing once and applying it to different blanks let them test each style without committing to a full run.',
  },
  {
    slug: 'good-people-advisory',
    title: 'Good People Advisory',
    thumbnail: '/images/work/GoodPeopleAdvisoryBack.png',
    images: ['/images/work/GoodPeopleAdvisoryBack.png'],
    tags: ['Advisory', 'Lifestyle'],
    year: 2024,
    productionModel: 'traditional',
    context: 'Corporate client gifting with a curated size run—straightforward one-time order, no ongoing inventory needed.',
  },
  {
    slug: 'san-remo-not-like-us',
    title: 'San Remo Not Like Us',
    thumbnail: '/images/work/SanRemoNotLikeUs.png',
    images: ['/images/work/SanRemoNotLikeUs.png'],
    tags: ['Music', 'Culture'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Music venue selling merch across multiple events—screen printing to transfer sheets made it easy to restock between shows and apply to whatever garments were trending.',
  },
  {
    slug: 'sf-fsu-design',
    title: 'SF FSU Design',
    thumbnail: '/images/work/SFFSU.png',
    images: ['/images/work/SFFSU.png'],
    tags: ['College', 'SF'],
    year: 2024,
    productionModel: 'traditional',
    context: 'Alumni watch party tee with a known attendee list—bulk order with a hard deadline, done.',
  },
  {
    slug: 'brit-since-96',
    title: 'Brit Since 96',
    thumbnail: '/images/work/BritSince96.png',
    images: ['/images/work/BritSince96.png'],
    tags: ['Vintage', 'Year'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Small streetwear brand running a design across multiple drops—paying for the screen printing once and applying it to different blanks meant the same print carried through the whole season as styles sold through.',
  },
  {
    slug: 'hermosa-ink',
    title: 'Hermosa Ink Pinup Tee',
    thumbnail: '/images/work/hermosa-ink-colorways.jpg',
    images: ['/images/work/hermosa-ink-colorways.jpg'],
    tags: ['Tattoo', 'Art', 'Colorways'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Tattoo shop launching a signature artist tee across six colorways—printing to transfer sheets meant one screen printing run covered every color option without locking into any specific blank.',
  },
  {
    slug: 'coach-damon',
    title: 'Coach Damon Wrap Em Up Tee',
    thumbnail: '/images/work/coach-damon-colorways.jpg',
    images: ['/images/work/coach-damon-colorways.jpg'],
    tags: ['Sports', 'Creator', 'Colorways'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Sports trainer launching merch with two colorways and no idea which would move—screen printing to transfers first let him test both before committing to blank quantities.',
  },
  {
    slug: 'wildherness',
    title: 'Wildherness Graphic Tee',
    thumbnail: '/images/work/wildherness-colorways.jpg',
    images: ['/images/work/wildherness-colorways.jpg'],
    tags: ['Outdoor', 'Lifestyle', 'Colorways'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Outdoor lifestyle brand wanted to test five colorways before committing to inventory. One screen printing run covered them all—they ordered blanks as each color sold through.',
  },
  {
    slug: 'solo-leveling-twitchcon',
    title: 'Solo Leveling Overdrive x TwitchCon',
    thumbnail: '/images/work/solo-leveling-twitchcon.jpg',
    images: ['/images/work/solo-leveling-twitchcon.jpg', '/images/work/solo-leveling-twitchcon-white.jpg'],
    tags: ['Gaming', 'Event', 'Convention'],
    year: 2024,
    productionModel: 'mobile',
    context: 'Gaming brand needed merch at TwitchCon without taking on inventory risk. We ran the booth, brought both colorways, and handled sales on site—they left with zero leftover stock.',
  },
  {
    slug: 'stubhub-open-distribution',
    title: 'StubHub x Open Distribution Cap',
    thumbnail: '/images/work/stubhub-open-distribution.jpg',
    images: ['/images/work/stubhub-open-distribution.jpg'],
    tags: ['Corporate', 'Collab', 'Cap'],
    year: 2024,
    productionModel: 'traditional',
    context: 'Corporate collab with a defined gifting list and a hard delivery date—traditional bulk order was the obvious call.',
  },
  {
    slug: 'love-is-punk-rock',
    title: 'Love Is Punk Rock Trucker Hat',
    thumbnail: '/images/work/love-is-punk-rock-colorways.jpg',
    images: ['/images/work/love-is-punk-rock-colorways.jpg'],
    tags: ['Music', 'Hat', 'Colorways'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Punk label dropping the same logo across four hat colorways—applying the same screen-printed patch to different blanks kept costs down and let them gauge which colors their crowd actually wanted.',
  },
  {
    slug: 'fsu-seminole-la',
    title: 'FSU Seminole Club LA',
    thumbnail: '/images/work/fsu-seminole-la-grey.jpg',
    images: ['/images/work/fsu-seminole-la-grey.jpg'],
    tags: ['College', 'Alumni', 'Club'],
    year: 2024,
    productionModel: 'traditional',
    context: 'Chapter-specific alumni tee with a confirmed member list and watch party date—one order, one delivery, done.',
  },
  {
    slug: 'eagles-nest-britannia',
    title: 'Eagles Nest West x Britannia Pub',
    thumbnail: '/images/work/eagles-nest-britannia-green.jpg',
    images: ['/images/work/eagles-nest-britannia-green.jpg'],
    tags: ['Club', 'Bar', 'Event'],
    year: 2025,
    productionModel: 'mobile',
    context: 'Fan club activation at a pub watch party—we ran a pop-up booth at the venue, handled all sales, and the club kept the upside without touching any inventory.',
  },
  {
    slug: 'cc-surface-restoration',
    title: 'CC Surface Restoration',
    thumbnail: '/images/work/cc-surface-restoration.jpg',
    images: ['/images/work/cc-surface-restoration.jpg'],
    tags: ['Local Business', 'Uniform', 'Branded'],
    year: 2025,
    productionModel: 'traditional',
    context: 'Local service business needing branded crew tees—defined headcount, consistent colorway, single run.',
  },
];

export const partners: Partner[] = [
  { name: 'Sony Pictures', logo: '/images/partners/sony.png' },
  { name: 'Colony', logo: '/images/partners/colony.png' },
  { name: 'FSU SF', logo: '/images/partners/fsu-sf.webp' },
  { name: 'Brit', logo: '/images/partners/brit.webp' },
  { name: 'Good People', logo: '/images/partners/good-people.webp' },
  { name: 'San Remo', logo: '/images/partners/san-remo.webp' },
];