import { WorkItem, Partner } from './types';

export const siteCopy = {
  headline: 'YOUR MERCH PARTNER.',
  subhead:
    'Most printers take your order and hand it back. We work alongside you to figure out the right production model—and put our own resources on the line to make it work.',
};

export const services = [
  {
    id: 'traditional',
    title: 'Traditional Production',
    tagline: 'The model you already know.',
    body: 'We work with you on the design—you pick your garments, sizes, colors, and quantities, and we decorate everything and deliver. No ongoing commitment, no leftover stock to manage. Best when you know what you need and just want it done.',
    icon: '01',
  },
  {
    id: 'flexible',
    title: 'Flexible Merch Production',
    tagline: 'Your screen printing, applied on your schedule.',
    body: 'Pay for your screen printing upfront and we print to transfer sheets instead of onto garments—so the same artwork applies to any blank, any time. Order t-shirts this month, hoodies next, or a new colorway whenever demand calls for it. Quantity pricing on the printing without having to predict what you\'ll need or when.',
    icon: '02',
  },
  {
    id: 'mobile',
    title: 'Mobile Merch',
    tagline: 'We Bring The Shop. You Bring The Demand. We Split The Profit.',
    body: 'Pay for your screen printing plus an operational deposit covering our labor, travel, and event overhead—we bring the equipment, staff the booth, and apply prints on-site. We stock and reuse the blank garments ourselves across events. Sales return your deposit first, then we split what\'s left—and you walk away with nothing left to store or sell.',
    icon: '03',
    featured: true,
  },
];

export const recentWork: WorkItem[] = [
  {
    slug: 'gwen-stefani-anaheim-tank',
    title: 'Gwen Stefani — No Doubt Sphere Residency',
    thumbnail: '/images/work/gwen-stefani-anaheim-tank.jpg',
    images: ['/images/work/gwen-stefani-anaheim-tank.jpg'],
    tags: ['Celebrity', 'One-of-One', 'Custom'],
    year: 2026,
    productionModel: 'traditional',
    context: 'A one-of-one commission for Gwen Stefani to wear during No Doubt\'s residency at the Sphere in Anaheim. We were hired to faithfully recreate a handmade tank top she originally wore in an early music video — requiring precise design reconstruction, custom color matching, special handling for the designer blank, and close coordination with our print vendor to produce a garment that could stand up to the original.',
  },
  {
    slug: 'hermosa-ink-summer-26',
    title: 'Hermosa Ink — Summer \'26 Tee',
    thumbnail: '/images/work/hermosa-ink-summer-26-front-back.jpg',
    images: ['/images/work/hermosa-ink-summer-26-front-back.jpg'],
    tags: ['Tattoo', 'Artist', 'Apparel'],
    year: 2026,
    productionModel: 'flexible',
    context: 'Summer 2026 merch for Hermosa Ink — minimal calligraphic "CES / cogito ergo sum" chest logo on front, intricate ornate back graphic with bird skull, flames, and Okenkouken branding. Single gray ink on white Comfort Colors, printed to transfers for flexible restocking.',
  },
  {
    slug: 'humungulus-records-setsuko',
    title: 'Humungulus Records — Setsuko Tee',
    thumbnail: '/images/work/humungulus-setsuko-front-back.jpg',
    images: ['/images/work/humungulus-setsuko-front-back.jpg'],
    tags: ['Music', 'Artist', 'Apparel'],
    year: 2026,
    productionModel: 'traditional',
    context: 'A collab shirt for Setsuko and Seita — a band on the Humungulus Records label — printed for their show. Front features an illustrative back print with "We Can Be Fragile Together," front chest has the Humungulus Records mark. Single red ink on mustard Comfort Colors, traditional run for the event.',
  },
  {
    slug: 'drip-king-la',
    title: 'Drip King LA',
    thumbnail: '/images/work/drip-king-la.jpeg',
    images: ['/images/work/drip-king-la.jpeg'],
    tags: ['Streetwear', 'Brand', 'LA', 'Live Event'],
    year: 2026,
    productionModel: 'mobile',
    context: 'DripKingLA is a well-known LA graffiti artist. We joined him at a live painting event and ran a Mobile Merch booth right alongside him — selling limited edition tees while he painted. The design captures the culture he\'s known for: lowriders, palm trees, the Metro, the city. Customers walked away with a piece tied to the moment.',
  },
  {
    slug: 'take-a-break-kazu',
    title: 'Take a Break — Kazu',
    thumbnail: '/images/work/take-a-break-kazu.jpeg',
    images: ['/images/work/take-a-break-kazu.jpeg'],
    tags: ['Artist', 'Music', 'Apparel'],
    year: 2026,
    productionModel: 'traditional',
    context: 'Take a Break with Kazu is a well-known podcast that interviews musicians and covers album reviews. They were launching merch for the first time to offer their fans — illustrative chest print on a Comfort Colors white tee, traditional run.',
  },
  {
    slug: 'sof-tattoo-owl-tank',
    title: 'Sof Tattoo — Owl Tank',
    thumbnail: '/images/work/sof-tattoo-owl-tank.png',
    images: ['/images/work/sof-tattoo-owl-tank.png'],
    tags: ['Artist', 'Tattoo', 'Apparel'],
    year: 2026,
    productionModel: 'traditional',
    context: 'Tattoo artist building a merch line around their flash art. The geometric owl design translated from skin to garment — white on black tank, single ink color, high-detail line work that required precise film output to hold at print size.',
  },
  {
    slug: 'blumeria-powerlines',
    title: 'Blumeria — Powerlines Tee',
    thumbnail: '/images/work/blumeria-powerlines.jpeg',
    images: ['/images/work/blumeria-powerlines.jpeg'],
    tags: ['Artist', 'Music', 'Apparel'],
    year: 2026,
    productionModel: 'flexible',
    context: 'Merch for Blumeria — minimal, photography-inspired front print on a Comfort Colors black tee. Clean single-color white print with a handwritten logotype. Printed to transfers for flexible restocking between shows.',
  },
  {
    slug: 'penn-vs-usc-showdown',
    title: 'Penn State vs USC Tailgate Tee',
    thumbnail: '/images/work/PennXUSC.png',
    images: ['/images/work/PennXUSC.png'],
    tags: ['College', 'Event Tee', 'Rivalry'],
    year: 2024,
    productionModel: 'traditional',
    context: 'One-time rivalry event with a fixed date and known headcount—traditional bulk order was the right fit.',
  },
  {
    slug: 'colony-cinco-anos',
    title: 'Colony Ghost Kitchen — 5th Anniversary',
    thumbnail: '/images/work/ColonyCincoAnosFront.png',
    images: ['/images/work/ColonyCincoAnosFront.png'],
    tags: ['Food', 'Anniversary', 'Small Business'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Ghost kitchen celebrating five years in business. Printing to transfer sheets let them sell tees to loyal customers in small batches without committing to a full inventory run.',
  },
  {
    slug: 'eagles-nest-west',
    title: 'Eagles Nest West Club Tee',
    thumbnail: '/images/work/EaglesNestWestFront.png',
    images: ['/images/work/EaglesNestWestFront.png', '/images/work/EaglesNestWestBack.png'],
    tags: ['Club', 'Lifestyle', 'Celebrity'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Eagles Nest West is the official Eagles fan club of Los Angeles, based out of Britannia Pub in Santa Monica. Their club tee ended up on Jason Kelce, who wore it on New Heights — the podcast he co-hosts with his brother Travis Kelce — after purchasing one from the club. Flexible printing gave them the ability to restock across watch parties without reordering the artwork each time.',
  },
  {
    slug: 'interstellar',
    title: 'Interstellar Restaurant & Coffee',
    thumbnail: '/images/work/InterstellarFront.png',
    images: ['/images/work/InterstellarFront.png', '/images/work/InterstellarBack.png'],
    tags: ['Coffee', 'Restaurant', 'Small Business'],
    year: 2024,
    productionModel: 'traditional',
    context: 'Small restaurant and coffee shop wanting branded tees for their team—clean design, small batch, one run.',
  },
  {
    slug: 'philthy-design',
    title: 'Eagles x Brit — Philthy Collab Tee',
    thumbnail: '/images/work/brit-philthy-tee-natural-front-back.jpg',
    images: ['/images/work/brit-philthy-tee-natural-front-back.jpg'],
    tags: ['Eagles', 'Football', 'Collab'],
    year: 2025,
    productionModel: 'flexible',
    context: 'A collab between Eagles Nest West and Britannia Pub to mark an iconic moment in the Eagles\' Super Bowl winning season. Demand was so high it sold out every batch—flexible printing meant they could restock quickly without reordering the artwork.',
  },
  {
    slug: 'good-people-advisory',
    title: 'Good People Coffee',
    thumbnail: '/images/work/GoodPeopleAdvisoryBack.png',
    images: ['/images/work/GoodPeopleAdvisoryBack.png'],
    tags: ['Coffee', 'Small Business', 'Community'],
    year: 2024,
    productionModel: 'traditional',
    context: 'Local minority and female owned coffee shop wanted branded tees for their staff and regulars—small batch, one run.',
  },
  {
    slug: 'san-remo-not-like-us',
    title: 'San Remo Barista Competition Tee',
    thumbnail: '/images/work/SanRemoNotLikeUs.png',
    images: ['/images/work/SanRemoNotLikeUs.png'],
    tags: ['Coffee', 'Competition', 'Corporate'],
    year: 2024,
    productionModel: 'traditional',
    context: 'San Remo, an Italian coffee machine manufacturer, needed event tees for a barista competition they were sponsoring—set headcount, one delivery, done.',
  },
  {
    slug: 'sf-fsu-design',
    title: 'SF FSU Design',
    thumbnail: '/images/work/SFFSU.png',
    images: ['/images/work/SFFSU.png'],
    tags: ['College', 'SF'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Alumni fan club using the same design across multiple SF watch parties—paying for the screen printing upfront let them apply prints to new blanks each season without reordering the artwork.',
  },
  {
    slug: 'brit-since-96',
    title: 'Britannia Pub — Since \'96',
    thumbnail: '/images/work/BritSince96.png',
    images: ['/images/work/BritSince96.png'],
    tags: ['Bar', 'Pub', 'Anniversary'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Britannia Pub celebrating their anniversary with a merch run—printing to transfer sheets let them restock tees across multiple events without reordering the artwork.',
  },
  {
    slug: 'hermosa-ink',
    title: 'Hermosa Ink Pinup Tee',
    thumbnail: '/images/work/hermosa-ink-colorways.jpg',
    images: ['/images/work/hermosa-ink-colorways.jpg'],
    tags: ['Tattoo', 'Art', 'Colorways'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Tattoo shop launching a signature artist tee across six colorways—printing to transfer sheets meant one screen printing run covered every color option without locking into any specific blank.',
  },
  {
    slug: 'coach-damon',
    title: 'Coach Damon Wrap Em Up Tee',
    thumbnail: '/images/work/coach-damon-colorways.jpg',
    images: ['/images/work/coach-damon-colorways.jpg'],
    tags: ['College', 'FSU', 'Parody'],
    year: 2024,
    productionModel: 'traditional',
    context: 'One-off parody drop for an FSU alumni club—limited run, single delivery, not meant to repeat.',
  },
  {
    slug: 'wildherness',
    title: 'Wildherness Graphic Tee',
    thumbnail: '/images/work/wildherness-colorways.jpg',
    images: ['/images/work/wildherness-colorways.jpg'],
    tags: ['Nonprofit', 'Women', 'Outdoor'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Women\'s nonprofit introducing more women to hunting, fishing, and camping. Printing to transfer sheets let them offer their design across multiple colorways without over-ordering—important when you\'re a nonprofit watching every dollar.',
  },
  {
    slug: 'solo-leveling-twitchcon',
    title: 'Solo Leveling Overdrive x TwitchCon',
    thumbnail: '/images/work/solo-leveling-twitchcon.jpg',
    images: ['/images/work/solo-leveling-twitchcon.jpg', '/images/work/solo-leveling-twitchcon-white.jpg'],
    tags: ['Gaming', 'Event', 'Convention'],
    year: 2024,
    productionModel: 'traditional',
    context: 'Gaming brand needed event tees for TwitchCon in two colorways—defined convention date, known order size, single run.',
  },
  {
    slug: 'stubhub-open-distribution',
    title: 'StubHub x Open Distribution Cap',
    thumbnail: '/images/work/stubhub-open-distribution.jpg',
    images: ['/images/work/stubhub-open-distribution.jpg'],
    tags: ['Corporate', 'Collab', 'Cap'],
    year: 2024,
    productionModel: 'traditional',
    context: 'Small batch for one internal team on a tight turnaround—we hit the deadline with no minimum quantity requirements.',
  },
  {
    slug: 'love-is-punk-rock',
    title: 'Love Is Punk Rock Trucker Hat',
    thumbnail: '/images/work/love-is-punk-rock-colorways.jpg',
    images: ['/images/work/love-is-punk-rock-colorways.jpg'],
    tags: ['Music', 'Hat', 'Colorways'],
    year: 2024,
    productionModel: 'flexible',
    context: 'An original 687 design. Printing to transfer sheets let us produce small batches for different events on demand—same artwork, applied whenever and wherever we needed it.',
  },
  {
    slug: 'fsu-seminole-la',
    title: 'FSU Seminole Club LA',
    thumbnail: '/images/work/fsu-seminole-la-grey.jpg',
    images: ['/images/work/fsu-seminole-la-grey.jpg'],
    tags: ['College', 'Alumni', 'Club'],
    year: 2024,
    productionModel: 'flexible',
    context: 'Alumni fan club chapter sharing the same design across multiple events—prints bought upfront and applied to blanks as the season progressed.',
  },
  {
    slug: 'eagles-nest-britannia',
    title: 'Eagles Nest West x Britannia Pub',
    thumbnail: '/images/work/eagles-nest-britannia-green.jpg',
    images: ['/images/work/eagles-nest-britannia-green.jpg'],
    tags: ['Club', 'Bar', 'Event'],
    year: 2025,
    productionModel: 'flexible',
    context: 'Eagles Nest West running the same design at the Britannia Pub—screen printing to transfers let them restock each watch party without having to reorder.',
  },
  {
    slug: 'cc-surface-restoration',
    title: 'CC Surface Restoration',
    thumbnail: '/images/work/cc-surface-restoration.jpg',
    images: ['/images/work/cc-surface-restoration.jpg'],
    tags: ['Local Business', 'Uniform', 'Branded'],
    year: 2025,
    productionModel: 'traditional',
    context: 'Local service business needing branded crew tees—defined headcount, consistent colorway, single run.',
  },
];

export const partners: Partner[] = [
  { name: 'Sony Pictures', logo: '/images/partners/sony.png' },
  { name: 'Colony', logo: '/images/partners/colony.png' },
  { name: 'FSU SF', logo: '/images/partners/fsu-sf.webp' },
  { name: 'Brit', logo: '/images/partners/brit.webp' },
  { name: 'Good People', logo: '/images/partners/good-people.webp' },
  { name: 'San Remo', logo: '/images/partners/san-remo.webp' },
];